import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5000/');
  await page.getByText('Admin quản lý tập trung Chỉ').click();
  await page.getByRole('heading', { name: 'Giao diện thân thiện, thao tá' }).click();
  await page.getByRole('textbox', { name: 'Họ và tên' }).click();
  await page.getByRole('textbox', { name: 'Họ và tên' }).fill('khánh');
  await page.getByRole('textbox', { name: 'Họ và tên' }).press('Tab');
  await page.getByRole('textbox', { name: 'Số điện thoại' }).fill('0985363602');
  await page.getByRole('textbox', { name: 'Số điện thoại' }).press('Tab');
  await page.getByRole('textbox', { name: 'Email' }).fill('khanhuu@gmail.com');
  await page.getByLabel('Loại bằng').selectOption('A1');
  await page.locator('#registrationForm div').filter({ hasText: 'Ghi chú' }).click();
  await page.getByRole('textbox', { name: 'Ghi chú' }).click();
  await page.getByRole('textbox', { name: 'Ghi chú' }).fill('ok nha');
  await page.getByRole('button', { name: 'Gửi đăng ký' }).click();
  await page.getByRole('link', { name: 'Đăng nhập', exact: true }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('ad');
  await page.getByRole('textbox', { name: 'Email' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Email' }).dblclick();
  await page.getByRole('textbox', { name: 'Email' }).dblclick();
  await page.getByRole('textbox', { name: 'Email' }).fill('admin@drivingschool.vn');
  await page.getByRole('textbox', { name: 'Mật khẩu' }).click();
  await page.getByRole('textbox', { name: 'Mật khẩu' }).fill('admin@drivingschool.vn');
  await page.getByRole('textbox', { name: 'Mật khẩu' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Mật khẩu' }).fill('Admin@123');
  await page.getByRole('button', { name: 'Đăng nhập' }).click();
  await page.getByRole('textbox', { name: 'Từ ngày' }).fill('2026-12-06');
  await page.getByRole('button', { name: 'Cập nhật dashboard' }).click();
  await page.getByRole('button', { name: 'Cập nhật dashboard' }).click();
  await page.getByLabel('Loại bằng').selectOption('A1');
  await page.getByLabel('Loại bằng').selectOption('A2');
  await page.getByLabel('Loại bằng').selectOption('B1');
  await page.getByRole('link', { name: 'Học viên' }).click();
  await page.getByRole('textbox', { name: 'Tên học viên' }).click();
  await page.getByRole('textbox', { name: 'Tên học viên' }).fill('khanh');
  await page.getByRole('textbox', { name: 'Tên học viên' }).press('Tab');
  await page.getByRole('textbox', { name: 'Email' }).fill('khanh@test.com');
  await page.getByRole('button', { name: 'Thêm học viên' }).click();
  await page.getByPlaceholder('Tên, số điện thoại, email').click();
  await page.getByPlaceholder('Tên, số điện thoại, email').fill('khanh');
  await page.getByPlaceholder('Tên, số điện thoại, email').click();
  await page.getByPlaceholder('Tên, số điện thoại, email').click();
  await page.getByPlaceholder('Tên, số điện thoại, email').click();
  await page.getByPlaceholder('Tên, số điện thoại, email').click();
  await page.getByPlaceholder('Tên, số điện thoại, email').click();
  await page.getByPlaceholder('Tên, số điện thoại, email').click();
  await page.getByPlaceholder('Tên, số điện thoại, email').fill('');
  await page.locator('#registrationCourseFilterLocal').selectOption('B2');
  await page.locator('#registrationCourseFilterLocal').selectOption('A1');
  await page.locator('#registrationCourseFilterLocal').selectOption('');
  await page.getByPlaceholder('Tên, số điện thoại, email').click();
  await page.getByRole('link', { name: 'Bài học' }).click();
  await page.getByRole('textbox', { name: 'Tên bài học' }).click();
  await page.getByRole('link', { name: 'Bài học' }).click();
  await page.getByRole('main').click();
  await page.getByRole('textbox', { name: 'Giải thích' }).press('F12');
  await page.getByText('Câu hỏi quiz bài học Câu hỏi sau khi học viên xem video bài học. 0 câu Bài học').click();
  await page.getByRole('textbox', { name: 'Tên bài học' }).fill('khánh');
  await page.getByRole('textbox', { name: 'Mô tả' }).fill('khánh');
  await page.getByRole('spinbutton', { name: 'Thứ tự' }).fill('61');
  await page.getByRole('spinbutton', { name: 'Điểm đạt quiz' }).fill('1');
  await page.getByRole('textbox', { name: 'URL video bài học' }).fill('youtube.com');
  await page.goto('http://localhost:5000/admin-lessons.html');
  await page.getByRole('button', { name: 'Upload ảnh' }).click();
  await page.getByLabel('Bài học', { exact: true }).selectOption('lesson_1781753097400_454ef982');
  await page.getByRole('textbox', { name: 'Nội dung câu hỏi' }).click();
  await page.getByRole('textbox', { name: 'Nội dung câu hỏi' }).fill('1');
  await page.getByLabel('Đáp án đúng').selectOption('D');
  await page.getByRole('button', { name: 'Upload ảnh' }).click();
  await page.getByRole('button', { name: 'Upload ảnh' }).setInputFiles('test.gif');
  await page.getByRole('button', { name: 'Upload ảnh' }).click();
  await page.getByRole('button', { name: 'Upload ảnh' }).setInputFiles('Untitled.png');
  await page.getByRole('textbox', { name: 'Đáp án A' }).click();
  await page.getByRole('textbox', { name: 'Đáp án A' }).fill('23');
  await page.getByRole('textbox', { name: 'Đáp án B' }).click();
  await page.getByRole('textbox', { name: 'Đáp án B' }).click();
  await page.getByRole('textbox', { name: 'Đáp án B' }).fill('3');
  await page.getByRole('textbox', { name: 'Đáp án C' }).click();
  await page.getByRole('textbox', { name: 'Đáp án C' }).fill('4');
  await page.getByRole('textbox', { name: 'Đáp án D' }).click();
  await page.getByRole('textbox', { name: 'Đáp án D' }).fill('5');
  await page.getByRole('textbox', { name: 'Giải thích' }).click();
  await page.getByRole('textbox', { name: 'Giải thích' }).fill('6');
  await page.getByRole('button', { name: 'Lưu câu hỏi' }).click();
  await page.getByRole('searchbox', { name: 'Tìm câu hỏi' }).click();
  await page.getByRole('searchbox', { name: 'Tìm câu hỏi' }).fill('khánh');
  await page.getByRole('searchbox', { name: 'Tìm câu hỏi' }).click();
  await page.getByRole('searchbox', { name: 'Tìm câu hỏi' }).click();
  await page.getByRole('searchbox', { name: 'Tìm câu hỏi' }).fill('test');
  await page.getByLabel('Lọc theo bài').selectOption('lesson_1781753097400_454ef982');
  await page.getByRole('searchbox', { name: 'Tìm câu hỏi' }).click();
  await page.getByRole('searchbox', { name: 'Tìm câu hỏi' }).fill('');
  await page.getByRole('button', { name: 'Sửa' }).click();
  await page.locator('.text-end > .btn.btn-sm.btn-outline-danger').click();
  await page.getByRole('button', { name: 'Xóa câu hỏi' }).click();
  await page.getByLabel('Lọc theo bài').selectOption('lesson_1780561498122_36a25679');
  await page.getByLabel('Lọc theo bài').selectOption('lesson_1781753097400_454ef982');
  await page.getByRole('link', { name: 'Kết quả' }).click();
  await page.getByRole('searchbox', { name: 'Tìm nhanh' }).click();
  await page.getByRole('searchbox', { name: 'Tìm nhanh' }).fill('khánh');
  await page.getByRole('searchbox', { name: 'Tìm nhanh' }).press('Enter');
  await page.getByLabel('Loại bằng').selectOption('B2');
  await page.getByLabel('Kenh thi').selectOption('theory');
  await page.getByLabel('Trạng thái').selectOption('failed');
  await page.getByText('Chưa đạt').nth(1).click();
  await page.getByLabel('Kenh thi').selectOption('third_party');
  await page.getByLabel('Loại bằng').selectOption('');
  await page.getByRole('searchbox', { name: 'Tìm nhanh' }).click();
  await page.getByRole('searchbox', { name: 'Tìm nhanh' }).fill('');
  await page.getByRole('row', { name: 'Dương Đình Khánh A1 3rd-party' }).getByRole('button').click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'Mở ảnh trong tab mới' }).click();
  const page1 = await page1Promise;
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByLabel('Số dòng mỗi trang').selectOption('10');
  await page.getByLabel('Số dòng mỗi trang').selectOption('20');
  await page.getByLabel('Số dòng mỗi trang').selectOption('50');
  await page.goto('http://localhost:5000/admin-theory.html');
  await page.getByRole('button', { name: 'Ảnh câu hỏi (có thể bỏ trống)' }).click();
  await page.getByRole('textbox', { name: 'Tên đề' }).click();
  await page.getByRole('textbox', { name: 'Tên đề' }).fill('khanh');
  await page.getByRole('spinbutton', { name: 'Điểm đạt' }).click();
  await page.getByRole('spinbutton', { name: 'Điểm đạt' }).fill('10');
  await page.getByRole('spinbutton', { name: 'Tổng câu' }).click();
  await page.getByRole('spinbutton', { name: 'Tổng câu' }).fill('10');
  await page.getByRole('button', { name: 'Lưu đề' }).click();
  await page.getByLabel('Đề thi').selectOption('exam_1781753356918_fe20a09c');
  await page.getByRole('checkbox', { name: 'Là câu điểm liệt' }).check();
  await page.getByLabel('Đáp án đúng').selectOption('D');
  await page.getByRole('textbox', { name: 'Nội dung câu hỏi' }).click();
  await page.getByRole('textbox', { name: 'Nội dung câu hỏi' }).fill('1');
  await page.getByRole('textbox', { name: 'Đáp án A' }).click();
  await page.getByRole('textbox', { name: 'Đáp án A' }).fill('2');
  await page.getByRole('textbox', { name: 'Đáp án B' }).click();
  await page.getByRole('textbox', { name: 'Đáp án A' }).fill('23');
  await page.getByRole('textbox', { name: 'Đáp án B' }).click();
  await page.getByRole('textbox', { name: 'Đáp án B' }).fill('34');
  await page.getByRole('textbox', { name: 'Đáp án C' }).click();
  await page.getByRole('textbox', { name: 'Đáp án C' }).fill('4');
  await page.getByRole('textbox', { name: 'Đáp án D' }).click();
  await page.getByRole('textbox', { name: 'Đáp án D' }).fill('56');
  await page.getByRole('textbox', { name: 'Giải thích hiện sau khi nộp' }).click();
  await page.getByRole('textbox', { name: 'Giải thích hiện sau khi nộp' }).fill('6');
  await page.getByRole('textbox', { name: 'Giải thích hiện sau khi nộp' }).click();
  await page.getByRole('button', { name: 'Ảnh câu hỏi (có thể bỏ trống)' }).click();
  await page.getByRole('button', { name: 'Ảnh câu hỏi (có thể bỏ trống)' }).setInputFiles('Untitled.png');
  await page.getByRole('button', { name: 'Lưu câu hỏi' }).click();
  await page.getByLabel('Đề thi').selectOption('exam_1781753356918_fe20a09c');
  await page.getByRole('button', { name: 'Xem ảnh' }).click();
  await page.getByRole('button', { name: 'Sửa' }).click();
  await page.getByRole('button', { name: 'Xóa' }).click();
  await page.getByRole('button', { name: 'Xóa câu hỏi' }).click();
  await page.getByRole('link', { name: 'Mô phỏng' }).click();
  await page.getByRole('textbox', { name: 'Tên bài mô phỏng' }).click();
  await page.getByRole('textbox', { name: 'Tên bài mô phỏng' }).fill('mo phong b2');
  await page.getByRole('textbox', { name: 'Mô tả' }).click();
  await page.getByRole('textbox', { name: 'Mô tả' }).fill('1');
  await page.getByRole('spinbutton', { name: 'Điểm đạt' }).click();
  await page.getByRole('spinbutton', { name: 'Điểm đạt' }).fill('3');
  await page.getByRole('spinbutton', { name: 'Tổng clip' }).click();
  await page.getByRole('spinbutton', { name: 'Tổng clip' }).fill('3');
  await page.getByRole('button', { name: 'Lưu bài mô phỏng' }).click();
  await page.getByLabel('Bài mô phỏng', { exact: true }).selectOption('sim_exam_1781753432328_fedc06e1');
  await page.getByRole('textbox', { name: 'Tên clip' }).click();
  await page.getByRole('textbox', { name: 'Tên clip' }).fill('1');
  await page.getByRole('textbox', { name: 'URL video' }).click();
  await page.getByRole('textbox', { name: 'URL video' }).fill('youtube.com');
  await page.getByRole('spinbutton', { name: 'Thứ tự' }).click();
  await page.getByRole('spinbutton', { name: 'Thứ tự' }).fill('1');
  await page.getByRole('spinbutton', { name: 'Bắt đầu tính điểm' }).click();
  await page.getByRole('spinbutton', { name: 'Bắt đầu tính điểm' }).fill('10');
  await page.getByRole('spinbutton', { name: 'Kết thúc tính điểm' }).click();
  await page.getByRole('spinbutton', { name: 'Kết thúc tính điểm' }).fill('19.9');
  await page.getByRole('button', { name: 'Lưu clip' }).click();
  await page.getByRole('button', { name: 'Sửa' }).nth(3).click();
  await page.getByRole('spinbutton', { name: 'Kết thúc tính điểm' }).click();
  await page.getByRole('spinbutton', { name: 'Kết thúc tính điểm' }).fill('15');
  await page.getByRole('button', { name: 'Lưu clip' }).click();
  await page.getByRole('button', { name: 'Xóa' }).nth(2).click();
  await page.getByRole('button', { name: 'Xóa clip' }).click();
  await page.getByRole('button', { name: 'Xóa' }).nth(3).click();
  const page3Promise = page.waitForEvent('popup');
  await page.getByRole('button', { name: 'Hủy' }).click();
  const page3 = await page3Promise;
  await page2.goto('https://www.facebook.com/daotaolaixehangha');
});